### ISSUE TITLE
::selection selektorundan istifadə edə bilərsiniz

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [yunisdev/YunisDEV.github.io#1]
[🔗](https://developer.mozilla.org/en-US/docs/Web/CSS/::selection)

```css
::selection {
    color: #fff;
    background-color: #816ed4;
}
```
Saytınızda qəşəng göründü.
